version: 2
jobs:
    build:
        working_directory: ~/tsuruclient-data-deploy
        docker:
            - image: node/11.3.0-stretch
        steps:
            - checkout
            - restore_cache:
                name: Restore Yarn Package Cache
                keys:
                    - yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                name: Install Dependencies
                command: yarn install --frozen-lockfile
            - save_cache:
                name: Save Yarn Package Cache
                key: yarn-packages-{{ checksum "yarn.lock" }}
                paths:
                    - ~/.cache/yarn
            - run:
                name: test
                command: echo "oh nothing"
            - run:
                name: build
                command: yarn build
            - run:
                name: deploy_build_branch
                command: |
                    git config credential.helper 'cache --timeout=120'
                    git config user.email "circleci@deployment.com"
                    git config user.name "Deployment Bot"
                    git add --all
                    git commit "deployment"
                    git push -q https://${}@github.com/tsuruclient/data.git deploy

workflows:
    jobs:
        - test
        - build
        - deploy_build_branch
            filters:
                branches:
                    only: master
